spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_secret}
  cloud:
    gateway:
      routes:
        - id: auth-service-public
          uri: ${AUTH_SERVICE_URL:http://auth-service:8081}
          predicates:
            - Path=/api/v1/auth/login,/api/v1/auth/refresh,/api/v1/auth/logout
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service
                fallbackUri: forward:/fallback/auth

        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8082}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://order-service:8083}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/fallback/order

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://payment-service:8084}
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackUri: forward:/fallback/payment

grpc:
  client:
    auth-service:
      address: 'static://${GRPC_AUTH_HOST:auth-service}:${GRPC_AUTH_PORT:9090}'
      negotiationType: plaintext

logging:
  level:
    com.example.innowise_vitali: ${APP_LOG_LEVEL:INFO}
    org.springframework.cloud.gateway: ${GATEWAY_LOG_LEVEL:WARN}