apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: online-store
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_MATCH_AUTH_SERVICE"
  INTERNAL_SECRET: "CHANGE_ME_MATCH_AUTH_SERVICE"
  REDIS_PASSWORD: "redis_pass"
